const express = require("express");
const router = express.Router();
const ControllerCatatanTrial = require("../controllers/controllerCatatanTrial");
const { authentication } = require("../middlewares/authentication");

router.get("/all-namaProduk01", ControllerCatatanTrial.findAllNamaProduct01);
router.get("/all-namaProduk02", ControllerCatatanTrial.findAllNamaProduct02);
router.get("/all-catatan-trial", ControllerCatatanTrial.findAllCatatanTrial);
router.post(
  "/create-catatanTrial",
  authentication,
  ControllerCatatanTrial.createCatatanTrial
);
router.get("/all-namaBahanBaku", ControllerCatatanTrial.findNamaBahanBaku);
router.post(
  "/create-komposisi-catatanTrial",
  ControllerCatatanTrial.createKomposisiCatatanTrial
);
router.post(
  "/create-perhitungan-zatAktif",
  ControllerCatatanTrial.createPerhitunganZatAktif
);
router.post(
  "/create-metode-pembuatan",
  ControllerCatatanTrial.createMetodePembuatan
);
router.post(
  "/create-proses-catatan-trial-padat",
  ControllerCatatanTrial.createProsesCatatanTrialPadat
);
router.post(
  "/create-proses-catatan-trial-penyalutan",
  ControllerCatatanTrial.createProsesCatatanTrialPenyalutan
);
router.post(
  "/create-formula-catatan-trial",
  ControllerCatatanTrial.createFormulaCatatanTrial
);
router.post(
  "/create-pengamatan-awal-cair",
  ControllerCatatanTrial.createPengamatanAwalCair
);
router.post(
  "/create-pengamatan-awal-steril",
  ControllerCatatanTrial.createPengamatanAwalSteril
);
router.post(
  "/create-pengamatan-awal-padat",
  ControllerCatatanTrial.createPengamatanAwalPadat
);
router.post(
  "/create-pengamatan-awal-penyalutan",
  ControllerCatatanTrial.createPengamatanAwalPenyalutan
);
router.post(
  "/create-pengamatan-lanjutan",
  ControllerCatatanTrial.createPengamatanLanjutan
);
router.put(
  "/update-catatanTrial/:id",
  ControllerCatatanTrial.updateCatatanTrial
);
router.put(
  "/update-komposisiCatatanTrial/:id",
  ControllerCatatanTrial.updateKomposisiCatatanTrial
);
router.put(
  "/update-perhitunganZatAktif/:id",
  ControllerCatatanTrial.updatePerhitunganZatAktif
);
router.put(
  "/update-formulaCatatanTrial/:id",
  ControllerCatatanTrial.updateFormulaCatatanTrial
);
router.put(
  "/update-metodePembuatan/:id",
  ControllerCatatanTrial.updateMetodePembuatan
);
router.put(
  "/update-pengamatanAwalCair/:id",
  ControllerCatatanTrial.updatePengamatanAwalCair
);
router.put(
  "/update-pengamatanAwalSteril/:id",
  ControllerCatatanTrial.updatePengamatanAwalSteril
);
router.put(
  "/update-pengamatanAwalLanjutan/:id",
  ControllerCatatanTrial.updatePengamatanAwalLanjutan
);
router.put(
  "/update-prosesCatatanTrialPadat/:id",
  ControllerCatatanTrial.updateProsesCatatanTrialPadat
);
router.put(
  "/update-pembahasan/:CatatanTrialID",
  ControllerCatatanTrial.updatePembahasan
);
router.put(
  "/update-kesimpulan/:CatatanTrialID",
  ControllerCatatanTrial.updateKesimpulan
);
router.put(
  "/update-tindakLanjut/:CatatanTrialID",
  ControllerCatatanTrial.updateTindakLanjut
);
router.get(
  "/get-komposisiNamaBahan/:id",
  ControllerCatatanTrial.getKomposisiNamaBahan
);
router.get(
  "/get-bentukSediaanCategoryCair",
  ControllerCatatanTrial.getBentukSediaanCategoryCair
);
router.get(
  "/get-bentukSediaanCategoryPadat",
  ControllerCatatanTrial.getBentukSediaanCategoryPadat
);
router.get(
  "/get-bentukSediaanCategorySteril",
  ControllerCatatanTrial.getBentukSediaanCategorySteril
);
router.get(
  "/get-filter-catatan-trial-padat",
  ControllerCatatanTrial.getFilterCatatanTrialPadat
);

router.get(
  "/catatan-trial/:id",
  authentication,
  ControllerCatatanTrial.getCatatanTrialDetails
);
router.get(
  "/catatan-trial-cair/:id",
  ControllerCatatanTrial.getCatatanTrialCairDetails
);
router.get(
  "/catatan-trial-padat/:id",
  ControllerCatatanTrial.getCatatanTrialPadatDetails
);
router.get(
  "/catatan-trial-steril/:id",
  ControllerCatatanTrial.getCatatanTrialSterilDetails
);
router.get(
  "/catatan-trial-penyalutan/:id",
  ControllerCatatanTrial.getCatatanTrialPenyalutanDetails
);

router.delete(
  "/delete-catatan-trial/:id",
  ControllerCatatanTrial.deleteCatatanTrial
);
router.delete(
  "/delete-prosesCatatanTrialPadat/:id",
  ControllerCatatanTrial.deleteProsesCatatanTrialPadat
);
router.delete(
  "/delete-komposisiCatatanTrial/:id",
  ControllerCatatanTrial.deleteKomposisiCatatanTrial
);
router.delete(
  "/delete-formulaCatatanTrial/:id",
  ControllerCatatanTrial.deleteFormulaCatatanTrial
);
router.delete(
  "/delete-metodePembuatan/:id",
  ControllerCatatanTrial.deleteMetodePembuatan
);
router.delete(
  "/delete-pengamatanAwalPadat/:id",
  ControllerCatatanTrial.deletePengamatanAwalPadat
);
router.delete(
  "/delete-pengamatanLanjutan/:id",
  ControllerCatatanTrial.deletePengamatanLanjutan
);
router.delete(
  "/delete-prosesPenyalutan/:id",
  ControllerCatatanTrial.deleteProsesPenyalutan
);
router.delete(
  "/delete-pengamatanAwalPenyalutan/:id",
  ControllerCatatanTrial.deletePengamatanAwalPenyalutan
);
router.put(
  "/approve-catatanTrial/:id",
  authentication,
  ControllerCatatanTrial.approveCatatanTrial
);

module.exports = router;
